-- ============================================================================
-- Migration: Create Property Embeddings Table
-- Nova Nest Real Estate - Vector Similarity Search
-- ============================================================================
--
-- Creates the property_embeddings table for storing OpenAI vector embeddings
-- to support semantic/similarity search via pgvector.
--
-- Embedding model: text-embedding-3-small (1536 dimensions)
-- Index type: HNSW with cosine similarity
--
-- Run AFTER: 009_create_master_migration.sql
-- Run with: psql -h <host> -U <user> -d <database> -f scripts/migrations/010_create_property_embeddings.sql
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. Enable pgvector Extension
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- 2. Create property_embeddings Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS property_embeddings (
  -- Primary key
  id                BIGSERIAL PRIMARY KEY,

  -- Reference to properties table (1:1 relationship)
  -- ON DELETE CASCADE ensures embeddings are cleaned up when property is deleted
  property_id       BIGINT NOT NULL UNIQUE REFERENCES properties(id) ON DELETE CASCADE,

  -- The vector embedding (1536 dims = OpenAI text-embedding-3-small)
  -- Nullable to allow inserting a row as a placeholder before the embedding is computed
  embedding         vector(1536),

  -- Which embedding model was used — allows selective re-generation when upgrading models
  embedding_model   TEXT NOT NULL DEFAULT 'text-embedding-3-small',

  -- Increment this to trigger batch re-embedding jobs without changing the model
  embedding_version INTEGER NOT NULL DEFAULT 1,

  -- MD5/SHA256 hash of the source text used to generate the embedding.
  -- Compare against current property text to detect stale embeddings cheaply,
  -- avoiding unnecessary OpenAI API calls.
  content_hash      TEXT,

  -- Language of the source text ('bg' or 'en')
  -- Nova Nest is bilingual; track which language was embedded
  source_language   TEXT NOT NULL DEFAULT 'bg' CHECK (source_language IN ('bg', 'en')),

  -- Timestamps
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- 3. HNSW Index for Cosine Similarity Search
-- ============================================================================
-- HNSW is preferred over IVFFlat: no need to pre-cluster, supports incremental
-- inserts, and performs well across all scales.
--
-- vector_cosine_ops — cosine distance is the standard metric for OpenAI embeddings.
-- m=16, ef_construction=64 are sensible defaults for a few thousand properties.

CREATE INDEX IF NOT EXISTS idx_property_embeddings_vector
  ON property_embeddings
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Standard B-tree index for lookups by property_id
CREATE INDEX IF NOT EXISTS idx_property_embeddings_property_id
  ON property_embeddings (property_id);

-- Index for filtering stale embeddings by model/version during re-embedding jobs
CREATE INDEX IF NOT EXISTS idx_property_embeddings_model_version
  ON property_embeddings (embedding_model, embedding_version);

-- ============================================================================
-- 4. updated_at Trigger
-- ============================================================================
-- Reuses the existing update_updated_at_column() function from 005_create_functions.sql

CREATE TRIGGER update_property_embeddings_updated_at
  BEFORE UPDATE ON property_embeddings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- 5. Comments
-- ============================================================================

COMMENT ON TABLE property_embeddings IS
  'Stores pgvector embeddings for property listings. Used for semantic similarity search. One row per property. Embeddings generated by OpenAI text-embedding-3-small (1536 dims).';

COMMENT ON COLUMN property_embeddings.embedding IS
  'Vector embedding of the property text (title + description). 1536 dimensions for text-embedding-3-small.';

COMMENT ON COLUMN property_embeddings.content_hash IS
  'Hash of the source text used to generate the embedding. Used to detect stale embeddings when property content changes.';

COMMENT ON COLUMN property_embeddings.embedding_version IS
  'Monotonically increasing version. Increment to schedule a batch re-embedding job across all rows.';

-- ============================================================================
-- 6. Row Level Security
-- ============================================================================

ALTER TABLE property_embeddings ENABLE ROW LEVEL SECURITY;

-- Public read access (anon + authenticated)
CREATE POLICY "property_embeddings_select_public"
  ON property_embeddings FOR SELECT
  TO anon, authenticated
  USING (true);

-- Write access: authenticated role only
CREATE POLICY "property_embeddings_insert_authenticated"
  ON property_embeddings FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "property_embeddings_update_authenticated"
  ON property_embeddings FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "property_embeddings_delete_authenticated"
  ON property_embeddings FOR DELETE
  TO authenticated
  USING (true);

COMMIT;
