-- ============================================================================
-- Migration: Create Neighborhood Embeddings Table
-- Nova Nest Real Estate - Vector Similarity Search
-- ============================================================================
--
-- Creates the neighborhood_embeddings table for storing OpenAI vector embeddings
-- to support semantic/similarity search via pgvector.
--
-- Embedding model: text-embedding-3-small (1536 dimensions)
-- Index type: HNSW with cosine similarity
--
-- Source text: name_bg + description + seo_description + seo_keywords
-- (or name_en for English embeddings)
--
-- Run AFTER: 010_create_property_embeddings.sql
-- Run with: psql -h <host> -U <user> -d <database> -f scripts/migrations/011_create_neighborhood_embeddings.sql
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. Enable pgvector Extension (safe no-op if already enabled)
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- 2. Create neighborhood_embeddings Table
-- ============================================================================

CREATE TABLE IF NOT EXISTS neighborhood_embeddings (
  -- Primary key
  id                BIGSERIAL PRIMARY KEY,

  -- Reference to neighborhoods table (1:1 relationship)
  -- ON DELETE CASCADE ensures embeddings are cleaned up when neighborhood is deleted
  neighborhood_id   BIGINT NOT NULL UNIQUE REFERENCES neighborhoods(id) ON DELETE CASCADE,

  -- The vector embedding (1536 dims = OpenAI text-embedding-3-small)
  -- Nullable to allow inserting a row as a placeholder before the embedding is computed
  embedding         vector(1536),

  -- Which embedding model was used — allows selective re-generation when upgrading models
  embedding_model   TEXT NOT NULL DEFAULT 'text-embedding-3-small',

  -- Increment this to trigger batch re-embedding jobs without changing the model
  embedding_version INTEGER NOT NULL DEFAULT 1,

  -- MD5/SHA256 hash of the source text used to generate the embedding.
  -- Compare against current neighborhood text to detect stale embeddings cheaply,
  -- avoiding unnecessary OpenAI API calls.
  content_hash      TEXT,

  -- Language of the source text ('bg' or 'en')
  -- Nova Nest is bilingual; track which language was embedded
  source_language   TEXT NOT NULL DEFAULT 'bg' CHECK (source_language IN ('bg', 'en')),

  -- Timestamps
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- 3. HNSW Index for Cosine Similarity Search
-- ============================================================================
-- HNSW is preferred over IVFFlat: no need to pre-cluster, supports incremental
-- inserts, and performs well across all scales.
--
-- vector_cosine_ops — cosine distance is the standard metric for OpenAI embeddings.
-- m=16, ef_construction=64 are sensible defaults for a small number of neighborhoods.

CREATE INDEX IF NOT EXISTS idx_neighborhood_embeddings_vector
  ON neighborhood_embeddings
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Standard B-tree index for lookups by neighborhood_id
CREATE INDEX IF NOT EXISTS idx_neighborhood_embeddings_neighborhood_id
  ON neighborhood_embeddings (neighborhood_id);

-- Index for filtering stale embeddings by model/version during re-embedding jobs
CREATE INDEX IF NOT EXISTS idx_neighborhood_embeddings_model_version
  ON neighborhood_embeddings (embedding_model, embedding_version);

-- ============================================================================
-- 4. updated_at Trigger
-- ============================================================================
-- Reuses the existing update_updated_at() function from 005_create_functions.sql

CREATE TRIGGER update_neighborhood_embeddings_updated_at
  BEFORE UPDATE ON neighborhood_embeddings
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- 5. Comments
-- ============================================================================

COMMENT ON TABLE neighborhood_embeddings IS
  'Stores pgvector embeddings for neighborhood listings. Used for semantic similarity search. One row per neighborhood. Embeddings generated by OpenAI text-embedding-3-small (1536 dims).';

COMMENT ON COLUMN neighborhood_embeddings.embedding IS
  'Vector embedding of the neighborhood text (name + description + seo fields). 1536 dimensions for text-embedding-3-small.';

COMMENT ON COLUMN neighborhood_embeddings.content_hash IS
  'Hash of the source text used to generate the embedding. Used to detect stale embeddings when neighborhood content changes.';

COMMENT ON COLUMN neighborhood_embeddings.embedding_version IS
  'Monotonically increasing version. Increment to schedule a batch re-embedding job across all rows.';

-- ============================================================================
-- 6. Row Level Security
-- ============================================================================

ALTER TABLE neighborhood_embeddings ENABLE ROW LEVEL SECURITY;

-- Public read access (anon + authenticated)
CREATE POLICY "neighborhood_embeddings_select_public"
  ON neighborhood_embeddings FOR SELECT
  TO anon, authenticated
  USING (true);

-- Write access: authenticated role only
CREATE POLICY "neighborhood_embeddings_insert_authenticated"
  ON neighborhood_embeddings FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "neighborhood_embeddings_update_authenticated"
  ON neighborhood_embeddings FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "neighborhood_embeddings_delete_authenticated"
  ON neighborhood_embeddings FOR DELETE
  TO authenticated
  USING (true);

COMMIT;
